### ISSUE TITLE
Support Kafka Headers as metadata in MarkLogic

### ISSUE THREAD

**Issue by gvidal0038** [marklogic/kafka-marklogic-connector#171]
It would be great to support headers from Kafka as MarkLogic Metadata

**Comment by BillFarber** [comment]
Hi Gary,
Just to confirm, you would like headers from the Kafka records to be stored as MarkLogic metadata values on the MarkLogic documents for those records?
Also, are you imagining that any and all headers would be stored that way, or would there be some subset of headers?

We do not currently have any plans for a new Kafka release in the near future. However, we will need to update to the latest Java client sometime soon, so it's conceivable we could add a feature at that time. It will depend on priorities.

**Comment by gvidal0038** [comment]
Yes Phil, that was my intention to support headers in Metadata. I forked repo and will add myself, maybe a pull request in future

**Comment by rjrudin** [comment]
@gvidal0038 We will be adding this soon (in the next few weeks) in a new minor release, as we have some dependencies that need updating to avoid security vulnerabilities.

**Comment by rjrudin** [comment]
Addressed in the 1.9.0 release
